### PR TITLE
WIP: Support nested keys

### PR DESCRIPTION
**Pull request by poteto**

### CODE REVIEW

**Comment by dpigera** [comment]
@poteto Do you have an ETA on when this will get merged ?

**Comment by poteto** [comment]
Sorry for the delay! Will get this over the line shortly.

**Comment by majnikov** [comment]
Hi @poteto , what about this PR?

**Comment by JCBarry** [comment]
Hi there! Just ran into needing this as well.  Is there a relevant workaround available?

**Comment by jbailey4** [comment]
@poteto Ran into this use case today, any idea when this could be merged? Glad to help with any work that may be needed.

**Comment by poteto** [comment]
Sorry, work keeps getting in the way :( If someone would like to help me get this over the line I would be very grateful! This is how I'm thinking this feature will be implemented:

1. Check if a key being set is nested
1. Check if the `change` object has the object(s) required to set that value
  - `true`: use `makeNestedObject` to create the object(s)
  - `false`: no-op
1. Set the value as normal
1. Tests

**Comment by jbailey4** [comment]
@poteto I'll take a look at this tonight and see where I get. The work should be based on what you already have here in the `feature/support-nested-keys` branch, correct?

**Comment by poteto** [comment]
Yup!

**Comment by jbailey4** [comment]
@poteto 

Update: struggling...

It seems changeset relies on the `setUnknownProperty` to kick off the validation and then ultimately apply the change/error, but this isn't happening when attempting to set a nested prop. Instead, Ember is calling `unknownProperty` with the nested object name (first item in the path), which then calls `_valueFor`. This returns the underlying nested object, which Ember then basically continues on setting the intended value, without changeset ever knowing.

As a baseline first test I have the following:

```es6
set(dummyModel, 'contact', { phoneNumber: 1112223333 });

let expectedResult = [ { key: 'contact', value: { phoneNumber: 9998887777 } } ];
let dummyChangeset = new Changeset(dummyModel);

dummyChangeset.set('contact.phoneNumber', 9998887777);

assert.deepEqual(get(dummyChangeset, 'changes'), expectedResult, 'precondition'));
```

**Comment by poteto** [comment]
I had another go at it with some inspiration from @jgwhite. 

However there are still some weird issues I'm trying to figure out

- [ ] Validate nested key
- [ ] Be able to set more than 1 root nested key
- [ ] Finish documentation

If anyone has any clues, please let me know...

**Comment by willrax** [comment]
hey @poteto, I'm trying to work on the points you wrote above. We would love to have nested validations in our application for a few "interesting" forms.

Are you committed to having this structure for the validations?

```js
{
 name: validateWhatever(),
 "address.street_name": validateWhatever()
}
```

It seems at the moment you can't access keys that contain dots within ember objects, so accessing the validator function is tricky.

I'm @willrax on Slack if you want to discuss in more detail.

**Comment by poteto** [comment]
I think the string option is the general practice in other ember validation libraries. I'm unsure what kind of extra complexity the object form would introduce, although in theory I think it should be the same code to retrieve the function via `Ember.get`

**Comment by willrax** [comment]
Ah right, If other libraries do it, it's probably best to stick to the convention then. I'll attempt to get the validations lookups (with the string keys) and that debugger in the tests at least hitting today.

**Comment by willrax** [comment]
Would you mind if we rebased (or merged) master in to this branch?

**Comment by willrax** [comment]
Had a quick look at some other libraries and it looks like internally they expand the string keys in to an object:

https://github.com/offirgolan/ember-cp-validations/blob/f0f8a92fdc2d09721b7acc4afd61fdbfae33e030/addon/validations/factory.js#L192

This gives people the string keys but then allows you to access the keys through the `get` `set` etc.

**Comment by poteto** [comment]
@willrax I don't mind! If you'd like, please open a PR merging into this branch `feature/support-nested-keys`

**Comment by minhnq013** [comment]
Hello, Just wondering if there is any news regarding this. 

I am currently encountering this issue and there are workaround but it would be awesome if we can do nested property validation.

**Comment by willrax** [comment]
hey @minhnq013 Yep, still working on this :+1:

**Comment by klclee** [comment]
HI @willrax @poteto looks like this is really close to done? Anything I can do to move this along? Could really do with it then having individual changeset for each nested model 👍

**Comment by rwwagner90** [comment]
Would also love to get this merged. I've got arrays in my changeset that don't rollback, which is annoying. Let me know if there is any way I can help!

**Comment by daohv** [comment]
Hi @poteto I use ember-changeset: 1.3.0 and ember-changeset-validation: 1.2.7 can not validate nested object. and also branches feature/nested-object also not work with validate nested object. Please confirm current status of bug not validate with nested object.

**Comment by MrGarry2016** [comment]
+1

**Comment by kalda341** [comment]
+1

**Comment by BorigTheDwarf** [comment]
Please +1

**Comment by DrJacobHolden** [comment]
+1

**Comment by shijistar** [comment]
+1

**Comment by frank06** [comment]
Ah, what a shame this does not work. Any workarounds in the meantime?

**Comment by greyhwndz** [comment]
@willrax thanks for looking into this. exciting coz it looks valuable for validating nested relationships. any updates on this?

**Comment by webark** [comment]
@willrax @poteto 
so it looks like why `Be able to set more than 1 root nested key` is not working, is due to the fact that when a property is set it calls [_setPath](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/property_set.js#L102) this then loops through the paths parts, [getting them recursivly](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/property_get.js#L81)

taking the example from the tests, 
```
    org: {
      asia: { sg: 'sg' },
      usa: {
        ca: 'ca',
        ny: 'ny',
        ma: { name: 'Massachusetts' }
      }
    }
```
if you first set the key `org.asia.sg` that will go through the changeset, which is empty at this time, and set the value of `org.asia.sg` in the changeset correctly. When we want to set`org.usa.ca` after that, if will loop through those parts, first trying to grap the `org` item, which actually is in our changeset, so it [returns the changeset](https://github.com/DockYard/ember-changeset/blob/master/addon/index.js#L551-L553) which doesn't have the `usa` property, which a non "deep set" can not handle.

The only path forward I can see at this time, would be to have the `CHANGES` property start out as a clone of the `CONTENT` and then when just the **"changes"** are needed process those out (which could be costly), but that seems like a fundamental change to the way that this addon behaves. But maybe (hopefully) there is soemthing that I am overlooking.

**Comment by webark** [comment]
@willrax @poteto I have a base of something working. I'd like to add more tests cause I'm not fully confident that every case is accounted for. This branch is fairly out of date, so I just recreated what was here and added a few things. Should I make a new PR, or merge it into this branch still https://github.com/DockYard/ember-changeset/compare/master...webark:master

**Comment by poteto** [comment]
@webark Nice work! Could you please PR into this branch once you've added more tests?

**Comment by webark** [comment]
@poteto I'll do that. Should i do a separate PR to get the branch uptodate with master also?

**Comment by webark** [comment]
I opened up the PR #192 in order to bring this branch up to master. Then I can open up [this PR](https://github.com/webark/ember-changeset/compare/feature/support-nested-keys...webark:feature/support-nested-keys_keyd-changes?expand=1)

I have validating of nested values and the ability to set more than one nested value working with tests. It appears that two-way binding seems to be lost on nested values, so there might need to be additional work on that.

**Comment by webark** [comment]
@willrax and @poteto If I could get another review on those PR's that would be great!

**Comment by webark** [comment]
@willrax @poteto or anyone else. I think I have all the cases covered in [this PR](https://github.com/webark/ember-changeset/compare/feature/support-nested-keys...webark:feature/support-nested-keys_keyd-changes?expand=1) I'd like to open up once #192 get's merged. There are some solutions that I'm not the most enthralled with, and wouldn't mind some more sets of eyes on it.

**Comment by rwwagner90** [comment]
@webark happy to take a look, but I don't have any better ideas, and it seems that it's a tough problem, since it's been open awhile.

**Comment by webark** [comment]
ya. @nkgm has been helping me test it out. Got one more bug and i think we are good to go after that!

**Comment by webark** [comment]
Ok. I think that last issue, that we know of so far, has been resolved. @poteto @willrax, or any other maintainer, is there anyway you think we could get #192 merged in so that this branch can be updated with the master branch, and then I can open up the PR for this branch? Right now the changes are a smattering of what this is changing and what has changed, so it's harder to get feedback.

**Comment by webark** [comment]
opened #194 with my changes to this feature to address the issues brought up in https://github.com/DockYard/ember-changeset/pull/140#issuecomment-284643868

**Comment by willrax** [comment]
Hey, just got some time to start looking through the code. I can test out the PR against this branch tomorrow and also have a think. Unfortunately, I'm not able to merge anything though.

**Comment by nrcjbarry** [comment]
Any updates on this PR? I'm currently doing a really hacky workaround so that my nested properties that contain arrays can be properly rolled back.

**Comment by webark** [comment]
@nrcjbarry does my fork in #194 help? If not, what's the data structure?

**Comment by rwwagner90** [comment]
Bump, need to get the amazing work by @webark reviewed and merged! Would be great to add him as a collaborator, and I am happy to review and help out any way I can!

**Comment by webark** [comment]
Still getting that ```Cannot find module 'is-absolute'
Error: Cannot find module 'is-absolute'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/ember-changeset/node_modules/npm/node_modules/which/which.js:12:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
error every other circle ci test. I'm unsure what in circle ci is causing this error.

**Comment by steverhoades** [comment]
Curious if this feature has made any additional headway and if not what are the remaining items to be completed?  Perhaps I can assist as I'd really like to see this introduced into Changeset.

**Comment by webark** [comment]
@steverhoades as far as I'm concerned, everything is working as expected. We've gone back and forth on some extra tests, and all of those have been added and resolved. I am unsure as to why the circle ci build errors are occurring, but I didn't run into any errors locally, or with Travis. THere are some merge conflicts, but those are easier for a maintainer to resolve due to the back and forth with doing PR's on to side branches, but if that is a blocker I am more the willing to issue a pr against the side branch to resolve those issues.

**Comment by rwwagner90** [comment]
@webark I vote we just remove circle and rely on travis, since that is the supported CI for Ember addons out of the box anyway.

**Comment by steverhoades** [comment]
@webark @rwwagner90 I'm getting the following error when attempting to use this branch:

```
Error: Property set failed: object in path "mykeyname" could not be found or was destroyed.
    at new EmberError (error.js:38)
    at setPath (ember-metal.js:2764)
    at set (ember-metal.js:2692)
    at Class.addError (index.js:341)
    at Class._setProperty (index.js:538)
    at Class._validateAndSet (index.js:467)
    at index.js:292
    at Array.map (<anonymous>)
    at Class.validate (index.js:291)
    at Class.submit (component.js:58)
```

I am running Ember 2.15 as well as ember-changset-validations v1.2.8.  I've also noticed that this branch is quite a bit behind master - does anyone have a rebased version of this branch somewhere?  My first attempt at rebasing didn't result in working code.

**Comment by steverhoades** [comment]
@webark @rwwagner90 Please disregard my last message.  I apologize, when i updated ember-changeset-validations it removed my link to ember-changeset.  I do not see this error with this branch.

**Comment by steverhoades** [comment]
@webark @rwwagner90 @poteto I have verified that this works beautifully in our app.  Would really like to see this released - how can I help?

**Comment by poteto** [comment]
I would like to remove CircleCI as well, but in a separate PR. Does anyone have the bandwidth to help with rebasing this and resolving merge conflicts?

**Comment by steverhoades** [comment]
@poteto I'm attempting this now.  If I can get something working i'll submit a PR.

**Comment by steverhoades** [comment]
@poteto @webark @rwwagner90 I've pushed a rebased version of this branch, tests are passing but I had to force update my branch and it will not cleanly integrate into this branch.  I'm gonna give it another shot to see if I can get a cleaner result.

See https://github.com/steverhoades/ember-changeset/commit/44aefc061014e2769a3d594ec4438768037f4090

**Comment by steverhoades** [comment]
@poteto @webark @rwwagner90 Ok, looks like this attempt is much much cleaner on the rebase side of things.. will provide PR.

https://github.com/steverhoades/ember-changeset/commit/d13917df6c583b67e7c93812d69521c007110ff7

**Comment by nucleartide** [comment]
Hey folks, since this is the issue/PR with the most activity, I'll try to find some time to review this and get it merged. As a newly appointed maintainer, I'd also like to start doing [monthly releases](https://github.com/poteto/ember-changeset/milestones) in order to close out all the issues/PRs.

Hope that's okay with everyone!

**Comment by rwwagner90** [comment]
@nucleartide sounds great! Glad to have you on board 😄

**Comment by nucleartide** [comment]
So I notice that this PR has some changes that aren't necessarily related to nested keys support. I'd like to break this PR into smaller ones, so the actual change is easier to review. 🙂 

It seems like `yarn test` is also failing on master – will take a look at that first.

**Comment by webark** [comment]
@nucleartide I was having issues with circle CI tests not passing, so I tried updating yarn and ember/ember-cli to see if that would resolve the issue, which it didn't. Feel free to pull out all the non-code changes, and put that into a separate PR.

**Comment by webark** [comment]
some of the other stuff is coming through due to a poor merge confict.

**Comment by webark** [comment]
@nucleartide I just created #211 

#211 is what this PR should be if it was able to be done in a cleaner way. (doing PR's against long-lived branches that are not up to date with master.. has complexities)

**Comment by poteto** [comment]
Closed by #211

**Pull request closed without merging**
