### PR TITLE
Safe set for setDeep

### LINKED ISSUE #468: Issue with @tracked
I am running into issues setting and consuming a changeset at the same time.

I have the following in a Glimmer component:
```js
// component.ts
export default class Dummy extends Component {
  @tracked changeset: BufferedChangeset;

  get otherProperty() {
    return this.changeset.property
  }
 
  @action
  setProperty() {
    this.changeset.set('property', {});
  }
}
```
```hbs
// template.hbs
{{log this.changeset.property}}
```

I get the following error:
```js
Error: Assertion Failed: You attempted to update [object Object].property to "[object Object]", but it is being tracked by a tracking context, such as a template, computed property, or observer. In order to make sure the context updates properly, you must invalidate the property when updating it. You can mark the property as `@tracked`, or use `@ember/object#set` to do this.
```

As you can see `changeset` is marked as `@tracked`, but that didn't seem to help.

If I just set the value, without consuming it in the template or another property, I don't get the error.

### PR DESCRIPTION
**Pull request by snewcomer**
close #468

### CODE REVIEW

**Comment by basz** [comment]
Not sure if this is *the* way to test this PR... Just giving some feedback...

// package.json
```
    "ember-bootstrap-changeset-validations": "^3.0.0",
    "ember-changeset": "git+https://github.com/poteto/ember-changeset.git#sn/safe-set-deep",
    "ember-changeset-validations": "^3.3.1",
```

Unfortunatly still seeing issue #468

**Comment by snewcomer** [comment]
@basz Would you mind trying again?  If you don't mind inspecting the node_modules and see if these changes made it in there?

**Comment by basz** [comment]
Hmm. Looks like the values are set correctly now... 🎉 However, for nested keys my validations don't seem to run... That could be because I'm coming from the v2 releases of

```
"ember-bootstrap-changeset-validations": "^2.0.0"
"ember-changeset": "^2.1.2",
"ember-changeset-validations": "^2.1.0",
```

anything obvious I should be aware of?

**Comment by snewcomer** [comment]
Awesome!  What does it mean that nested validations don't run?  If `user.email` are you setting `email` directly or setting `user` and expecting `email` validations to run?

**Comment by basz** [comment]
I'm confused.

should the validationsMap for nested keys be like version 2.

```js
{
  key1: [validations],
  key2.nested1: [validations],
}
```

or (nested pojo's)

```
{
  key1: [validations],
  key2: {
    nested1: [validations],
  }
}
```

**Comment by snewcomer** [comment]
nested pojo's.  Using the dot separated version was very limiting for cases detailed in places in #379

**Comment by basz** [comment]
ok thanks. 

We should change that on the README... Search for "specify nested keys with dot delimiters"...

**Comment by basz** [comment]
That solved the validation when I edit a field. When I submit the form I do the following

```
this.changeset.validate().then(() => {
      alert(this.changeset.get('isInvalid'));

      console.log(this.changeset.get('errors'));
    });
```
Errors is then empty, alert is false, whilst it shouldn't...

**Comment by snewcomer** [comment]
@basz If there was a minimal repo of this issue, would be happy to take a look!

**Comment by basz** [comment]
There seems to be a problem (or at least a difference between v2 and v3) with detecting the keys to be validated.

When calling `this.changeset.validate()` none of the validations aren run (which used to be all validtions). when I do `this.changeset.validate('consumer.name.givenname')` just that one and isInvalid becomes true...

**Comment by basz** [comment]
I could do something like https://github.com/hughsk/flat on the validationMap and feed it into the validate method... But I'll wait until you confirm it isn't something validate should do by itself and is indeed a difference between v2 and v3...

**Comment by snewcomer** [comment]
@basz Interesting!  We do have tests for `validate/0`.  I'd be curious on what part of `changeset.validate()` isn't working.

**Comment by basz** [comment]
Yeah, I went through the tests an found it...

It's not working on nested keys. So given;

```js
{
  'key1': [validations],
  'key2': {
    'nested1': [validations],
  }
}
```
and then calling `this.changeset.validate()` only runs the 'key1' validations... Not sure if that is intended though... (the test '#validate/nested validates nested fields immediately' specifically calls the nested key)

**Comment by basz** [comment]
currently working around with

```
validationKeys = Object.keys(flatten(dossierValidations))
      .map(key => key.slice(0, -2))
      .uniq();

this.changeset.validate(...validationKeys);
```

**Comment by snewcomer** [comment]
Oh interesting!  Mind filing an issue?  Nested keys have always been a sore spot.  By moving away from dot separated (v3), we solved most of the issues.  This just seems to be a missed edge by me.

**Comment by basz** [comment]
see https://github.com/poteto/ember-changeset/issues/478

**Comment by basz** [comment]
Thank you @snewcomer for fixing the latest issues and taking care of this package. My upgrade path has been smooth sailing since and ember-changeset is a pleasure to work with...

**Comment by snewcomer** [comment]
Thank you for the `flatten` idea!  Made the solution super simple.

**Pull request merged**
