### PR TITLE
User save test: create user without the profile

### PR DESCRIPTION
**Pull request by andreyfel**
Illustration of #403

### CODE REVIEW

**Comment by snewcomer** [comment]
Is this PR close-able?

**Comment by andreyfel** [comment]
@snewcomer I rebased it and it is still failing. I'm wondering if it is supposed to be supported in this way?
```
  changeset.set('profile', profile);
  changeset.set('profile.firstName', 'Grace');
```

**Comment by snewcomer** [comment]
Yeah it seems we can't do

```js
options.safeSet(Proxy, 'firstName', next.value);
```

I wonder why that is 🤔 There is probably something in the merge-deep util we need to look at...

**Comment by snewcomer** [comment]
What I am seeing is that you effectively have to set the `profile` on the user initially.  Based on what I understand, this is inherent to ED and not ember-changeset.  

This is a minor inconvenience; however, not solvable.  

At minimum, we can document our findings.  What do you think?

**Pull request closed without merging**
