### PR TITLE
Bump `@embroider/*` packages and add `peerDependencies` info

### PR DESCRIPTION
**Pull request by SergeAstapov**
Closes # .

## Changes proposed in this pull request

PR bumps `@embroider/macros` packages in `dependencies` similar to what was done in https://github.com/emberjs/ember-render-modifiers/pull/54#discussion_r768114222

Alongside `@embroider/macros` bump we should add `ember-data` to `peerDependencies` for proper resolution.

### CODE REVIEW

**Comment by SergeAstapov** [comment]
Seem like build failures caused by some changes in latest patch version of ember-data

@snewcomer wonder if you have some insights/ideas

**Comment by SergeAstapov** [comment]
seem like `await settled()` is needed after `changeset.execute()` (which under the hood runs `set()` onto relationship) when interacting with relationships.
Seem like caused by recent changes in ember-data.

@snewcomer if this looks good for you, do you mind to release new beta with this change?

**Comment by SergeAstapov** [comment]
`embroider-optimized` scenario failures caused by ember-data using `require()` which I assume should be replaced with `importSync` for embroider compatibility

**Comment by SergeAstapov** [comment]
Created PR to improve embroider story in Ember Data https://github.com/emberjs/data/pull/7849

**Review by snewcomer — APPROVED** [review]

**Comment by SergeAstapov** [comment]
@snewcomer do you mind to release this as `4.0.0-beta.2`?

**Pull request merged**
