### PR TITLE
Feature nest support

### PR DESCRIPTION
**Pull request by ppegusii**
@poteto I saw that you were working on support for nested objects and wanted to show you my WIP on the feature. It returns proxy objects when `_valueFor(key)` would return an object or array. The proxy objects returns get/set control back to changeset. Arrays of primitives don't yet work because Ember.ArrayProxy does not provide a proxy setter for an index AFAIK. I plan to try other proxies to address the issue.

### CODE REVIEW

**Comment by remithomas** [comment]
@ppegusii what about the typeof _instance_ ?

**Comment by ppegusii** [comment]
@remithomas good point. I'll add it.

**Comment by wmadden** [comment]
To completely support nesting of arrays and objects of arbitrary depth, `ember-changeset` would need to recurse through the properties of the object it wraps, as well as every value of any arrays. It might be better to exclude nesting this from the responsibilities of the library, since it adds a lot of complexity.

You could just throw an error if the consumer attempts to `set()` a property whose value is an object or array, so at least consumers will have a hint on how to handle it themselves (and not end up here or in #133).

**Comment by kevlarr** [comment]
Why not set an object/array property using `JSON.parse(JSON.stringify(...))`.. ?

Properties like this generally store data-only objects, not objects that contain functions.

**Comment by nucleartide** [comment]
Hey folks, since https://github.com/poteto/ember-changeset/pull/211 was merged, I'm going to go ahead and close this. :( Feel free to open a new PR if you have any additions.

**Pull request closed without merging**
