### PR TITLE
Fix merging array-like objects

### LINKED ISSUE #657: Setting a key in an array of objects transforms the array in changes into an object.
## Version

4.1.1

## Test Case

I made a failing test case in https://github.com/AmauryD/ember-changeset.

```ts
test('changes from validate stay an array when the property is set', async (assert) => {
    assert.expect(1);
    let initialData = { shipments: [] };
    const formQuoteSchemaValidation = object().shape({
      shipments: array(),
    });

    const changeset = ValidatedChangeset(initialData);

    changeset.set('shipments', [
      ...changeset.get('shipments'),
      {
        name: 'william',
      },
    ]);

    changeset.set('shipments.0.name', 'albium');

    await changeset.validate((changes) => {
      assert.true(Array.isArray(changes.shipments));
      return formQuoteSchemaValidation.validate(changes);
    });
  });
```

## Steps to reproduce

- Declare a changeset with an array of objects.
- Change the value of any of object's properties.
- The array in changes becomes an 'object' array.

```
{
    "0": {
        ...
    }
}
```

## Expected Behavior

The array in changes object should stay an array.

## Actual Behavior

The array in changes is transformed into an object.

## More

I'm using the new (experimental) changeset. But i think the problem is coming from the mergeDeep function that is overridden in this library. The test above passed in the validated-changeset repository.

Thank you,

### PR DESCRIPTION
**Pull request by AmauryD**
Closes #657 .

### CODE REVIEW

**Review by SergeAstapov — APPROVED** [review]

**Comment by snewcomer** [comment]
@AmauryD 1.3.4 has been published of validated-changeset!

**Comment by AmauryD** [comment]
> @AmauryD 1.3.4 has been published of validated-changeset!

Thanks, i updated the PR 😃

**Comment by AmauryD** [comment]
Forgot to update the lock file, it should pass now.

**Comment by AmauryD** [comment]
I don't really know what caused the last test to fail, it's probably related to the ci.

**Review by snewcomer — APPROVED** [review]

**Pull request merged**
