### PR TITLE
update ember-deep-set dependency

### LINKED ISSUE #319: update ember-deep-set dependency
the `ember-deep-set` direct dependency has been updated, this consumer should resolve the new dependency.

### PR DESCRIPTION
**Pull request by 0xadada**
related https://github.com/poteto/ember-deep-set/pull/15#issuecomment-428611523

closes #319

### CODE REVIEW

**Comment by 0xadada** [comment]
@snewcomer 🎉  here ya go

**Comment by snewcomer** [comment]
0.2.0 was published!

**Comment by snewcomer** [comment]
@0xadada Mind updaing the pkg.json and we can get this merged?

**Comment by 0xadada** [comment]
> @0xadada Mind updaing the pkg.json and we can get this merged?

@snewcomer all set

**Pull request merged**
