### PR TITLE
Bring back skipped tests

### PR DESCRIPTION
**Pull request by snewcomer**
ref #379 

@sandstrom - yes but only with `changeset.set('dogs', [...oldDogs, newDog])`

### CODE REVIEW

**Comment by sandstrom** [comment]
@snewcomer Awesome news, will look into it this afternoon! 😄

**Comment by rwwagner90** [comment]
@snewcomer @sandstrom is this saying you cannot do `addObject` or `pushObject` and must instead create a new array and set it on the changeset? We should document `hasMany` and `belongsTo` in the README probably?

**Comment by sandstrom** [comment]
@rwwagner90 That's how I understood it yes, but I'm not 100% sure

**Comment by snewcomer** [comment]
Some doc updates would probably be a good idea!  This is mainly due to our use of tracked (without track-built-ins)

**Comment by rwwagner90** [comment]
@snewcomer thanks for the clarification. Is this only for hasMany or is this any array? I can take a stab at writing some docs.

**Comment by snewcomer** [comment]
https://github.com/poteto/ember-changeset/blob/master/tests/integration/main-test.js#L187

Lmk if these tests are helpful at all and/or is different than what you though it should be!  And docs are always definitely appreciated!

**Pull request merged**
