### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by SergeAstapov**
Updates CHANGELOG.md with notes for 2.2.x versions

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@snewcomer do you think introduction of `lerna-changelog` and `release-it` (similar to what projects like [`ember-template-lint`](https://github.com/ember-template-lint/ember-template-lint) do) would be desirable?

**Comment by snewcomer** [comment]
I'd be fine with it!  What does the install/setup time look like?  Should we file an issue to do or is it pretty straightforward to setup?

**Comment by SergeAstapov** [comment]
@snewcomer I haven't done that setup yet, so I'm pretty unfamiliar.
I don't mind to file an issue and work on it as I'm pretty interested to have experience with such kind of tools. Though can't promise to finish it soon

**Comment by snewcomer** [comment]
That sounds good!  No rush.  #389 https://github.com/poteto/ember-changeset/issues/389

**Comment by herzzanu** [comment]
@SergeAstapov @snewcomer I can do this if you didn't start working on it. I've done it before and it's pretty trivial. Let me know.

**Comment by snewcomer** [comment]
@herzzanu That would be lovely!  I was hoping to learn from one of you on how to do it!

**Comment by herzzanu** [comment]
@snewcomer Awesome, just opened #426

**Pull request merged**
